//AUTH USER LOGIN
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_COMPLETED = "USER_LOGIN_COMPLETED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

//AUTH USER REGISTER
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";


//FETCH PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_COMPLETED = 'GET_PRODUCTS_COMPLETED';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

//FETCH SUB CATEGORY
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_COMPLETED = 'GET_CATEGORIES_COMPLETED';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

//FETCH SUB CATEGORY
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES';
export const GET_SUB_CATEGORIES_REQUEST = 'GET_SUB_CATEGORIES_REQUEST';
export const GET_SUB_CATEGORIES_COMPLETED = 'GET_SUB_CATEGORIES_COMPLETED';
export const GET_SUB_CATEGORIES_ERROR = 'GET_SUB_CATEGORIES_ERROR';

// CART ACTIONS
export const GET_CART = 'GET_CART';
export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_COMPLETED = 'GET_CART_COMPLETED';
export const GET_CART_ERROR = 'GET_CART_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_COMPLETED = 'ADD_TO_CART_COMPLETED';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_COMPLETED = 'REMOVE_FROM_CART_COMPLETED';
export const REMOVE_FROM_CART_ERROR = 'REMOVE_FROM_CART_ERROR';

export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';
export const UPDATE_CART_QTY_REQUEST = 'UPDATE_CART_QTY_REQUEST';
export const UPDATE_CART_QTY_COMPLETED = 'UPDATE_CART_QTY_COMPLETED';
export const UPDATE_CART_QTY_ERROR = 'UPDATE_CART_QTY_ERROR';

export const TOGGLE_CART_ITEM_SELECTION = 'TOGGLE_CART_ITEM_SELECTION';
export const CLEAR_CART = 'CLEAR_CART';

// COLLECTION ACTIONS
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTIONS_REQUEST = 'GET_COLLECTIONS_REQUEST';
export const GET_COLLECTIONS_COMPLETED = 'GET_COLLECTIONS_COMPLETED';
export const GET_COLLECTIONS_ERROR = 'GET_COLLECTIONS_ERROR';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_COMPLETED = 'CREATE_COLLECTION_COMPLETED';
export const CREATE_COLLECTION_ERROR = 'CREATE_COLLECTION_ERROR';

export const SWITCH_COLLECTION = 'SWITCH_COLLECTION';
export const SWITCH_COLLECTION_REQUEST = 'SWITCH_COLLECTION_REQUEST';
export const SWITCH_COLLECTION_COMPLETED = 'SWITCH_COLLECTION_COMPLETED';
export const SWITCH_COLLECTION_ERROR = 'SWITCH_COLLECTION_ERROR';

export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
export const DELETE_COLLECTION_COMPLETED = 'DELETE_COLLECTION_COMPLETED';
export const DELETE_COLLECTION_ERROR = 'DELETE_COLLECTION_ERROR';

// WISHLIST ACTIONS
export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';