//AUTH USER LOGIN
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_COMPLETED = "USER_LOGIN_COMPLETED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGIN_UI_RESET = "USER_LOGIN_UI_RESET";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_GOOGLE_LOGIN = "USER_GOOGLE_LOGIN";

//AUTH USER REGISTER
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";


//FETCH PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_COMPLETED = 'GET_PRODUCTS_COMPLETED';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

//FETCH SUB CATEGORY
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_COMPLETED = 'GET_CATEGORIES_COMPLETED';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

//FETCH SUB CATEGORY
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES';
export const GET_SUB_CATEGORIES_REQUEST = 'GET_SUB_CATEGORIES_REQUEST';
export const GET_SUB_CATEGORIES_COMPLETED = 'GET_SUB_CATEGORIES_COMPLETED';
export const GET_SUB_CATEGORIES_ERROR = 'GET_SUB_CATEGORIES_ERROR';

// CART ACTIONS
export const GET_CART = 'GET_CART';
export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_COMPLETED = 'GET_CART_COMPLETED';
export const GET_CART_ERROR = 'GET_CART_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_COMPLETED = 'ADD_TO_CART_COMPLETED';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_COMPLETED = 'REMOVE_FROM_CART_COMPLETED';
export const REMOVE_FROM_CART_ERROR = 'REMOVE_FROM_CART_ERROR';

export const UPDATE_CART_QTY = 'UPDATE_CART_QTY';
export const UPDATE_CART_QTY_REQUEST = 'UPDATE_CART_QTY_REQUEST';
export const UPDATE_CART_QTY_COMPLETED = 'UPDATE_CART_QTY_COMPLETED';
export const UPDATE_CART_QTY_ERROR = 'UPDATE_CART_QTY_ERROR';

export const EDIT_CART_ITEM = 'EDIT_CART_ITEM';
export const EDIT_CART_ITEM_REQUEST = 'EDIT_CART_ITEM_REQUEST';
export const EDIT_CART_ITEM_COMPLETED = 'EDIT_CART_ITEM_COMPLETED';
export const EDIT_CART_ITEM_ERROR = 'EDIT_CART_ITEM_ERROR';

export const TOGGLE_CART_ITEM_SELECTION = 'TOGGLE_CART_ITEM_SELECTION';
export const SET_CART_ITEMS_SELECTION = 'SET_CART_ITEMS_SELECTION';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_PURCHASED_CART_ITEMS = 'REMOVE_PURCHASED_CART_ITEMS';

// COLLECTION ACTIONS
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTIONS_REQUEST = 'GET_COLLECTIONS_REQUEST';
export const GET_COLLECTIONS_COMPLETED = 'GET_COLLECTIONS_COMPLETED';
export const GET_COLLECTIONS_ERROR = 'GET_COLLECTIONS_ERROR';

export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_COMPLETED = 'CREATE_COLLECTION_COMPLETED';
export const CREATE_COLLECTION_ERROR = 'CREATE_COLLECTION_ERROR';

export const SWITCH_COLLECTION = 'SWITCH_COLLECTION';
export const SWITCH_COLLECTION_REQUEST = 'SWITCH_COLLECTION_REQUEST';
export const SWITCH_COLLECTION_COMPLETED = 'SWITCH_COLLECTION_COMPLETED';
export const SWITCH_COLLECTION_ERROR = 'SWITCH_COLLECTION_ERROR';

export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
export const DELETE_COLLECTION_COMPLETED = 'DELETE_COLLECTION_COMPLETED';
export const DELETE_COLLECTION_ERROR = 'DELETE_COLLECTION_ERROR';

// WISHLIST ACTIONS
export const GET_WISHLIST = 'GET_WISHLIST';
export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_COMPLETED = 'GET_WISHLIST_COMPLETED';
export const GET_WISHLIST_ERROR = 'GET_WISHLIST_ERROR';
export const MERGE_GUEST_WISHLIST = 'MERGE_GUEST_WISHLIST';

export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST';
export const TOGGLE_WISHLIST_REQUEST = 'TOGGLE_WISHLIST_REQUEST';
export const TOGGLE_WISHLIST_COMPLETED = 'TOGGLE_WISHLIST_COMPLETED';
export const TOGGLE_WISHLIST_ERROR = 'TOGGLE_WISHLIST_ERROR';
export const TOGGLE_WISHLIST_LOCAL = 'TOGGLE_WISHLIST_LOCAL';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

// CUSTOMER ACTIONS
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST';
export const GET_CUSTOMER_COMPLETED = 'GET_CUSTOMER_COMPLETED';
export const GET_CUSTOMER_ERROR = 'GET_CUSTOMER_ERROR';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_COMPLETED = 'UPDATE_CUSTOMER_COMPLETED';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';

// ADDRESS ACTIONS
export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST';
export const GET_ADDRESSES_COMPLETED = 'GET_ADDRESSES_COMPLETED';
export const GET_ADDRESSES_ERROR = 'GET_ADDRESSES_ERROR';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_COMPLETED = 'CREATE_ADDRESS_COMPLETED';
export const CREATE_ADDRESS_ERROR = 'CREATE_ADDRESS_ERROR';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_COMPLETED = 'UPDATE_ADDRESS_COMPLETED';
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_COMPLETED = 'DELETE_ADDRESS_COMPLETED';
export const DELETE_ADDRESS_ERROR = 'DELETE_ADDRESS_ERROR';

// WALLET ACTIONS
export const GET_WALLET = 'GET_WALLET';
export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST';
export const GET_WALLET_COMPLETED = 'GET_WALLET_COMPLETED';
export const GET_WALLET_ERROR = 'GET_WALLET_ERROR';

// REWARD ACTIONS
export const GET_REWARDS = 'GET_REWARDS';
export const GET_REWARDS_REQUEST = 'GET_REWARDS_REQUEST';
export const GET_REWARDS_COMPLETED = 'GET_REWARDS_COMPLETED';
export const GET_REWARDS_ERROR = 'GET_REWARDS_ERROR';

// REDEMPTION ACTIONS
export const GET_REDEMPTIONS = 'GET_REDEMPTIONS';
export const GET_REDEMPTIONS_REQUEST = 'GET_REDEMPTIONS_REQUEST';
export const GET_REDEMPTIONS_COMPLETED = 'GET_REDEMPTIONS_COMPLETED';
export const GET_REDEMPTIONS_ERROR = 'GET_REDEMPTIONS_ERROR';

export const CREATE_REDEMPTION = 'CREATE_REDEMPTION';
export const CREATE_REDEMPTION_REQUEST = 'CREATE_REDEMPTION_REQUEST';
export const CREATE_REDEMPTION_COMPLETED = 'CREATE_REDEMPTION_COMPLETED';
export const CREATE_REDEMPTION_ERROR = 'CREATE_REDEMPTION_ERROR';

// ORDER ACTIONS
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_COMPLETED = 'GET_ORDERS_COMPLETED';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_COMPLETED = 'GET_ORDER_DETAILS_COMPLETED';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_COMPLETED = 'CREATE_ORDER_COMPLETED';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_COMPLETED = 'CANCEL_ORDER_COMPLETED';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_COMPLETED = 'DELETE_ORDER_COMPLETED';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';

export const REORDER_ORDER = 'REORDER_ORDER';
export const REORDER_ORDER_REQUEST = 'REORDER_ORDER_REQUEST';
export const REORDER_ORDER_COMPLETED = 'REORDER_ORDER_COMPLETED';
export const REORDER_ORDER_ERROR = 'REORDER_ORDER_ERROR';

// NOTIFICATION ACTIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_COMPLETED = 'GET_NOTIFICATIONS_COMPLETED';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const SOCKET_REALTIME_REFRESH = 'SOCKET_REALTIME_REFRESH';
/** Connect or reconnect Socket.IO when a persisted session is restored. */
export const SOCKET_ENSURE_CONNECTED = 'SOCKET_ENSURE_CONNECTED';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';