export const ROUTES = {
    HOME: 'Home' as const,
    CART: 'Cart' as const,
    WISHLIST: 'Wishlist' as const,
    ORDER: 'Order' as const,
    ORDER_MANAGEMENT: 'OrderManagement' as const,
    LEAVE_REVIEW: 'LeaveReview' as const,
    PRODUCT_DETAILS: 'ProductDetails' as const,
    CATEGORY_PRODUCTS: 'CategoryProducts' as const,
    SEARCH: 'Search' as const,
    PROFILE: 'Profile' as const,
    LOGIN: 'Login' as const,
    REGISTER: 'Register' as const,
    FORGOT_PASSWORD: 'ForgotPassword' as const,
    RESEND_VERIFICATION: 'ResendVerification' as const,
    RESET_PASSWORD: 'ResetPassword' as const,
    NOTIFICATION: 'Notification' as const,
    ORDER_SUCCESS: 'OrderSuccess' as const,
    CHECKOUT: 'Checkout' as const,
    MANAGE_ADDRESSES: 'ManageAddresses' as const,
    EDIT_ADDRESS: 'EditAddress' as const,
    CHOOSE_DELIVERY_ADDRESS: 'ChooseDeliveryAddress' as const,
    CHOOSE_DELIVERY: 'ChooseDelivery' as const,
    CHOOSE_PAYMENT_METHOD: 'ChoosePaymentMethod' as const,
    PAYMENT_METHODS: 'PaymentMethods' as const,
    ADD_PAYMENT_METHOD: 'AddPaymentMethod' as const,
    PROMOS_VOUCHERS: 'PromosVouchers' as const,
    WALLET: 'Wallet' as const,
    REWARDS: 'Rewards' as const,
    SUSTAINABILITY_STORY: 'SustainabilityStory' as const,
    APP_APPEARANCE: 'AppAppearance' as const,
    APPEARANCE_PICKER: 'AppearancePicker' as const,
    ACCOUNT_SECURITY: 'AccountSecurity' as const,
    CHANGE_PASSWORD: 'ChangePassword' as const,
    ERROR: 'Error' as const,
};

export default ROUTES;
